// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['desktopapp']['App']['CancelDownload'](arg1);
}

export function CancelSearchRequests() {
  return window['go']['desktopapp']['App']['CancelSearchRequests']();
}

export function CancelSubmission(arg1) {
  return window['go']['desktopapp']['App']['CancelSubmission'](arg1);
}

export function ClearCompletedDownloads() {
  return window['go']['desktopapp']['App']['ClearCompletedDownloads']();
}

export function ClearCompletedSubmissions(arg1) {
  return window['go']['desktopapp']['App']['ClearCompletedSubmissions'](arg1);
}

export function ClearQueue() {
  return window['go']['desktopapp']['App']['ClearQueue']();
}

export function DiagnosticState() {
  return window['go']['desktopapp']['App']['DiagnosticState']();
}

export function EnqueueDownloads(arg1, arg2, arg3) {
  return window['go']['desktopapp']['App']['EnqueueDownloads'](arg1, arg2, arg3);
}

export function EnsureGuestSession() {
  return window['go']['desktopapp']['App']['EnsureGuestSession']();
}

export function GetBuildInfo() {
  return window['go']['desktopapp']['App']['GetBuildInfo']();
}

export function GetKeywordSuggestions(arg1) {
  return window['go']['desktopapp']['App']['GetKeywordSuggestions'](arg1);
}

export function GetQueueSnapshot() {
  return window['go']['desktopapp']['App']['GetQueueSnapshot']();
}

export function GetReleaseStatus() {
  return window['go']['desktopapp']['App']['GetReleaseStatus']();
}

export function GetSession() {
  return window['go']['desktopapp']['App']['GetSession']();
}

export function GetUnreadSubmissionCount() {
  return window['go']['desktopapp']['App']['GetUnreadSubmissionCount']();
}

export function GetUsernameSuggestions(arg1) {
  return window['go']['desktopapp']['App']['GetUsernameSuggestions'](arg1);
}

export function GetWatching() {
  return window['go']['desktopapp']['App']['GetWatching']();
}

export function GetWorkspaceState() {
  return window['go']['desktopapp']['App']['GetWorkspaceState']();
}

export function LoadMoreResults(arg1, arg2) {
  return window['go']['desktopapp']['App']['LoadMoreResults'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['desktopapp']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['desktopapp']['App']['Logout']();
}

export function OpenDownloadDirectory() {
  return window['go']['desktopapp']['App']['OpenDownloadDirectory']();
}

export function OpenExternalURL(arg1) {
  return window['go']['desktopapp']['App']['OpenExternalURL'](arg1);
}

export function PauseAllDownloads() {
  return window['go']['desktopapp']['App']['PauseAllDownloads']();
}

export function PickDownloadDirectory() {
  return window['go']['desktopapp']['App']['PickDownloadDirectory']();
}

export function ProxyAvatarImageURL(arg1) {
  return window['go']['desktopapp']['App']['ProxyAvatarImageURL'](arg1);
}

export function RefreshSearch(arg1) {
  return window['go']['desktopapp']['App']['RefreshSearch'](arg1);
}

export function ResumeAllDownloads() {
  return window['go']['desktopapp']['App']['ResumeAllDownloads']();
}

export function RetryAllDownloads() {
  return window['go']['desktopapp']['App']['RetryAllDownloads']();
}

export function RetryDownload(arg1) {
  return window['go']['desktopapp']['App']['RetryDownload'](arg1);
}

export function RetrySubmission(arg1) {
  return window['go']['desktopapp']['App']['RetrySubmission'](arg1);
}

export function SaveWorkspaceState(arg1) {
  return window['go']['desktopapp']['App']['SaveWorkspaceState'](arg1);
}

export function Search(arg1) {
  return window['go']['desktopapp']['App']['Search'](arg1);
}

export function SkipReleaseTag(arg1) {
  return window['go']['desktopapp']['App']['SkipReleaseTag'](arg1);
}

export function StopAllDownloads() {
  return window['go']['desktopapp']['App']['StopAllDownloads']();
}

export function UpdateRatings(arg1) {
  return window['go']['desktopapp']['App']['UpdateRatings'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['desktopapp']['App']['UpdateSettings'](arg1);
}
