// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktopapp} from '../models';

export function CancelDownload(arg1:string):Promise<desktopapp.QueueSnapshot>;

export function CancelSubmission(arg1:string):Promise<desktopapp.QueueSnapshot>;

export function ClearCompletedDownloads():Promise<desktopapp.QueueSnapshot>;

export function ClearQueue():Promise<desktopapp.QueueSnapshot>;

export function DiagnosticState():Promise<string>;

export function EnqueueDownloads(arg1:string,arg2:desktopapp.DownloadSelection,arg3:desktopapp.DownloadOptions):Promise<desktopapp.QueueSnapshot>;

export function EnsureGuestSession():Promise<desktopapp.SessionInfo>;

export function GetKeywordSuggestions(arg1:string):Promise<Array<string>>;

export function GetQueueSnapshot():Promise<desktopapp.QueueSnapshot>;

export function GetReleaseStatus():Promise<desktopapp.ReleaseStatus>;

export function GetSession():Promise<desktopapp.SessionInfo>;

export function GetUnreadSubmissionCount():Promise<number>;

export function GetUsernameSuggestions(arg1:string):Promise<Array<desktopapp.UsernameSuggestion>>;

export function GetWatching():Promise<Array<desktopapp.UsernameSuggestion>>;

export function LoadMoreResults(arg1:string,arg2:number):Promise<desktopapp.SearchResponse>;

export function Login(arg1:string,arg2:string):Promise<desktopapp.SessionInfo>;

export function Logout():Promise<desktopapp.SessionInfo>;

export function OpenDownloadDirectory():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function PickDownloadDirectory():Promise<string>;

export function RefreshSearch(arg1:string):Promise<desktopapp.SearchResponse>;

export function RetryDownload(arg1:string):Promise<desktopapp.QueueSnapshot>;

export function RetrySubmission(arg1:string):Promise<desktopapp.QueueSnapshot>;

export function Search(arg1:desktopapp.SearchParams):Promise<desktopapp.SearchResponse>;

export function SkipReleaseTag(arg1:string):Promise<desktopapp.AppSettings>;

export function StopAllDownloads():Promise<desktopapp.QueueSnapshot>;

export function UpdateRatings(arg1:string):Promise<desktopapp.SessionInfo>;

export function UpdateSettings(arg1:desktopapp.AppSettings):Promise<desktopapp.AppSettings>;
