// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {state} from '../models';
import {url} from '../models';

export function CancelDownload(arg1:string):Promise<types.QueueSnapshot>;

export function CancelSearchRequests(arg1:string):Promise<void>;

export function CancelSubmission(arg1:string):Promise<types.QueueSnapshot>;

export function ClearCompletedDownloads():Promise<types.QueueSnapshot>;

export function ClearCompletedSubmissions(arg1:Array<string>):Promise<types.QueueSnapshot>;

export function ClearQueue():Promise<types.QueueSnapshot>;

export function ConfigureRemoteStarter(arg1:state.RemoteStarter):Promise<void>;

export function DebugResetState(arg1:string):Promise<types.DebugResetResult>;

export function DiagnosticState():Promise<string>;

export function DisableRemoteAccess():Promise<types.RemoteAccessInfo>;

export function EnableRemoteAccess():Promise<types.RemoteAccessInfo>;

export function EnqueueDownloads(arg1:string,arg2:types.DownloadSelection,arg3:types.DownloadOptions):Promise<types.QueueSnapshot>;

export function EnsureGuestSession():Promise<types.SessionInfo>;

export function GetBuildInfo():Promise<types.BuildInfo>;

export function GetKeywordSuggestions(arg1:string):Promise<Array<types.KeywordSuggestion>>;

export function GetQueueSnapshot():Promise<types.QueueSnapshot>;

export function GetReleaseStatus():Promise<types.ReleaseStatus>;

export function GetRemoteAccessInfo():Promise<types.RemoteAccessInfo>;

export function GetSession():Promise<types.SessionInfo>;

export function GetSubmissionDescription(arg1:string):Promise<types.SubmissionDescription>;

export function GetUnreadSubmissionCount():Promise<number>;

export function GetUsernameSuggestions(arg1:string):Promise<Array<types.UsernameSuggestion>>;

export function GetWatching():Promise<Array<types.UsernameSuggestion>>;

export function GetWorkspaceState():Promise<types.WorkspaceState>;

export function LoadMoreResults(arg1:string,arg2:number,arg3:string):Promise<types.SearchResponse>;

export function Login(arg1:string,arg2:string):Promise<types.SessionInfo>;

export function Logout():Promise<types.SessionInfo>;

export function OpenDownloadDirectory():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function PauseAllDownloads():Promise<types.QueueSnapshot>;

export function PickDownloadDirectory():Promise<string>;

export function ProxyAvatarImageURL(arg1:string):Promise<string>;

export function RefreshSearch(arg1:string,arg2:string):Promise<types.SearchResponse>;

export function ResolveApprovedRemoteURL(arg1:string):Promise<url.URL>;

export function ResolveRemoteURL(arg1:string):Promise<string>;

export function ResumeAllDownloads():Promise<types.QueueSnapshot>;

export function RetryAllDownloads():Promise<types.QueueSnapshot>;

export function RetryDownload(arg1:string):Promise<types.QueueSnapshot>;

export function RetrySubmission(arg1:string):Promise<types.QueueSnapshot>;

export function SaveWorkspaceState(arg1:types.WorkspaceState):Promise<void>;

export function Search(arg1:types.SearchParams):Promise<types.SearchResponse>;

export function SelectRemoteAccessHost(arg1:string):Promise<types.RemoteAccessInfo>;

export function SharedSnapshot():Promise<types.SharedSnapshot>;

export function SkipReleaseTag(arg1:string):Promise<types.AppSettings>;

export function StopAllDownloads():Promise<types.QueueSnapshot>;

export function SubscribeSharedEvents(arg1:number):Promise<any|any>;

export function UpdateRatings(arg1:string):Promise<types.SessionInfo>;

export function UpdateSettings(arg1:types.AppSettings):Promise<types.AppSettings>;
