// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['state']['App']['CancelDownload'](arg1);
}

export function CancelSearchRequests() {
  return window['go']['state']['App']['CancelSearchRequests']();
}

export function CancelSubmission(arg1) {
  return window['go']['state']['App']['CancelSubmission'](arg1);
}

export function ClearCompletedDownloads() {
  return window['go']['state']['App']['ClearCompletedDownloads']();
}

export function ClearCompletedSubmissions(arg1) {
  return window['go']['state']['App']['ClearCompletedSubmissions'](arg1);
}

export function ClearQueue() {
  return window['go']['state']['App']['ClearQueue']();
}

export function ConfigureRemoteStarter(arg1) {
  return window['go']['state']['App']['ConfigureRemoteStarter'](arg1);
}

export function DebugResetState(arg1) {
  return window['go']['state']['App']['DebugResetState'](arg1);
}

export function DiagnosticState() {
  return window['go']['state']['App']['DiagnosticState']();
}

export function DisableRemoteAccess() {
  return window['go']['state']['App']['DisableRemoteAccess']();
}

export function EnableRemoteAccess() {
  return window['go']['state']['App']['EnableRemoteAccess']();
}

export function EnqueueDownloads(arg1, arg2, arg3) {
  return window['go']['state']['App']['EnqueueDownloads'](arg1, arg2, arg3);
}

export function EnsureGuestSession() {
  return window['go']['state']['App']['EnsureGuestSession']();
}

export function GetBuildInfo() {
  return window['go']['state']['App']['GetBuildInfo']();
}

export function GetKeywordSuggestions(arg1) {
  return window['go']['state']['App']['GetKeywordSuggestions'](arg1);
}

export function GetQueueSnapshot() {
  return window['go']['state']['App']['GetQueueSnapshot']();
}

export function GetReleaseStatus() {
  return window['go']['state']['App']['GetReleaseStatus']();
}

export function GetRemoteAccessInfo() {
  return window['go']['state']['App']['GetRemoteAccessInfo']();
}

export function GetSession() {
  return window['go']['state']['App']['GetSession']();
}

export function GetUnreadSubmissionCount() {
  return window['go']['state']['App']['GetUnreadSubmissionCount']();
}

export function GetUsernameSuggestions(arg1) {
  return window['go']['state']['App']['GetUsernameSuggestions'](arg1);
}

export function GetWatching() {
  return window['go']['state']['App']['GetWatching']();
}

export function GetWorkspaceState() {
  return window['go']['state']['App']['GetWorkspaceState']();
}

export function LoadMoreResults(arg1, arg2) {
  return window['go']['state']['App']['LoadMoreResults'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['state']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['state']['App']['Logout']();
}

export function OpenDownloadDirectory() {
  return window['go']['state']['App']['OpenDownloadDirectory']();
}

export function OpenExternalURL(arg1) {
  return window['go']['state']['App']['OpenExternalURL'](arg1);
}

export function PauseAllDownloads() {
  return window['go']['state']['App']['PauseAllDownloads']();
}

export function PickDownloadDirectory() {
  return window['go']['state']['App']['PickDownloadDirectory']();
}

export function ProxyAvatarImageURL(arg1) {
  return window['go']['state']['App']['ProxyAvatarImageURL'](arg1);
}

export function RefreshSearch(arg1) {
  return window['go']['state']['App']['RefreshSearch'](arg1);
}

export function ResolveRemoteURL(arg1) {
  return window['go']['state']['App']['ResolveRemoteURL'](arg1);
}

export function ResumeAllDownloads() {
  return window['go']['state']['App']['ResumeAllDownloads']();
}

export function RetryAllDownloads() {
  return window['go']['state']['App']['RetryAllDownloads']();
}

export function RetryDownload(arg1) {
  return window['go']['state']['App']['RetryDownload'](arg1);
}

export function RetrySubmission(arg1) {
  return window['go']['state']['App']['RetrySubmission'](arg1);
}

export function SaveWorkspaceState(arg1) {
  return window['go']['state']['App']['SaveWorkspaceState'](arg1);
}

export function Search(arg1) {
  return window['go']['state']['App']['Search'](arg1);
}

export function SelectRemoteAccessHost(arg1) {
  return window['go']['state']['App']['SelectRemoteAccessHost'](arg1);
}

export function SharedSnapshot() {
  return window['go']['state']['App']['SharedSnapshot']();
}

export function SkipReleaseTag(arg1) {
  return window['go']['state']['App']['SkipReleaseTag'](arg1);
}

export function StopAllDownloads() {
  return window['go']['state']['App']['StopAllDownloads']();
}

export function SubscribeSharedEvents(arg1) {
  return window['go']['state']['App']['SubscribeSharedEvents'](arg1);
}

export function UpdateRatings(arg1) {
  return window['go']['state']['App']['UpdateRatings'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['state']['App']['UpdateSettings'](arg1);
}
